# Generated by Django 5.0.2 on 2024-02-24 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50, verbose_name='Überschrift')),
                ('content', models.TextField(verbose_name='Blog Eintrag')),
                ('rating', models.IntegerField(default=5, verbose_name='Bewertung')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Verändert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
